import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>Contact Us</h1>
    <p>Some random message goes here</p>

    <div id="contact-container">
      <div className='contact-info'>
        <h4>
          Contact Information
        </h4>
        <p>input text</p>
        <div className='icon-text'>
          <i class="fa fa-phone fa-2x" aria-hidden="true"></i>
          <span>phone number here</span>
        </div>
        <div className='icon-text'>
        <i class="fa fa-envelope-o" aria-hidden="true"></i>
          <span>email address here</span>
        </div>
        <div className='icon-text'>
        <i class="fa fa-map-marker" aria-hidden="true"></i>
          <span>Address here</span>
        </div>      
         <div className='social-media'>
          {/* <a href="#" className='icon-circle'>
            <i className='icon'></i>
            </a>             */}
          </div>
        </div>
      </div>

      <form>
        
      </form>
    </>
     
  
  )
}
